# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='signup',
        ),
    ]
