# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0004_auto_20171018_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
