# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0006_user_bday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bday',
        ),
    ]
