# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0017_auto_20171025_2032'),
        ('loginregis_app', '0015_auto_20171025_1159'),
    ]

    operations = [
    ]
