# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0025_auto_20171026_1837'),
        ('loginregis_app', '0020_auto_20171025_1751'),
    ]

    operations = [
    ]
