# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0029_auto_20171027_0310'),
        ('loginregis_app', '0026_merge_20171026_1349'),
    ]

    operations = [
    ]
