# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregis_app', '0034_auto_20171027_1704'),
        ('loginregis_app', '0034_auto_20171027_1236'),
    ]

    operations = [
    ]
